apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  selector:
    app: iris-api
  ports:
    - protocol: TCP
      port: 80 # External port for the service
      targetPort: 8200 # Port on the pod
  type: LoadBalancer # Exposes the service externally using a cloud load balancer
