name: Continuous Deployment to GKE

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the 'main' branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: iris-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: iris-api-deployment
  SERVICE_NAME: iris-api-service
  
  # --- IMPORTANT CHANGE HERE ---
  # Use the Artifact Registry host for the us-central1 multi-region
  IMAGE_HOST: us-central1-docker.pkg.dev 
  
  IMAGE_NAME: iris-api
  IMAGE_TAG: latest
  FULL_IMAGE_PATH: ${{ env.IMAGE_HOST }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate Docker to Artifact Registry
        # Authenticate with the specific Artifact Registry host
        run: gcloud auth configure-docker ${{ env.IMAGE_HOST }}

      - name: Build Docker image
        # Build using the full Artifact Registry image path
        run: docker build -t ${{ env.FULL_IMAGE_PATH }} .

      - name: Push Docker image to Artifact Registry
        # Push to the pre-created Artifact Registry repository
        run: docker push ${{ env.FULL_IMAGE_PATH }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

      - name: Deploy to GKE
        run: |
          # The sed command will replace the GCR placeholder with the full Artifact Registry path
          sed -i "s|gcr.io/\[YOUR_GCP_PROJECT_ID\]/iris-api:latest|${{ env.FULL_IMAGE_PATH }}|g" kubernetes/deployment.yaml

          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          echo "Waiting for deployment rollout to complete..."
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}

          echo "Service details:"
          kubectl get service ${{ env.SERVICE_NAME }}
